substitutions:
  _MY_VAR: 'world!'

steps:
  # - name: 'gcr.io/cloud-builders/pip'
  #   args: ['install', '-r', 'requirements.txt']
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      echo "Hello ${_MY_VAR}"
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world-flask', '.']
    id: build-docker

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world-flask']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'hello-world-flask', '--image', 'gcr.io/PROJECT_ID/hello-world-flask', '--region', 'europe-west1']


images:
  - 'gcr.io/$PROJECT_ID/hello-world-flask'

options:
  logging: 'CLOUD_LOGGING_ONLY'